apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: abhijithdockerhub/dotnet:latest # Replace with your Docker Hub image name
          ports:
            - containerPort: 80 # Adjust if your app listens on a different port
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 # The port the service will expose internally
      targetPort: 80 # The port the container listens on
  type: ClusterIP # This exposes the service within the cluster
