on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -t my-app .
      - name: Aqua Security Trivy 
        uses: aquasecurity/trivy-action@0.30.0
